ALTER TABLE "ReferralProgram"
  ALTER COLUMN "referrerReward" TYPE DOUBLE PRECISION,
  ALTER COLUMN "refereeReward" TYPE DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "rewardTrigger" TEXT NOT NULL DEFAULT 'first',
  ADD COLUMN IF NOT EXISTS "rewardType" TEXT NOT NULL DEFAULT 'FIXED',
  ADD COLUMN IF NOT EXISTS "multiLevel" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "levelRewards" JSONB,
  ADD COLUMN IF NOT EXISTS "stackWithRegistration" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "messageTemplate" TEXT,
  ADD COLUMN IF NOT EXISTS "placeholders" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
