version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: loyalty
      POSTGRES_PASSWORD: loyalty
      POSTGRES_DB: loyalty
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

volumes:
  pgdata:
