apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: loyalty
  labels:
    app: loyalty-api

data:
  NODE_ENV: "production"
  WORKERS_ENABLED: "0"
  NO_HTTP: "0"
  OTEL_ENABLED: "0"
  ANTIFRAUD_GUARD: "on"
  AF_LIMIT_MERCHANT: "200"
  AF_WINDOW_MERCHANT_SEC: "3600"
  AF_LIMIT_DEVICE: "20"
  AF_WINDOW_DEVICE_SEC: "600"
  AF_LIMIT_STAFF: "60"
  AF_WINDOW_STAFF_SEC: "600"
  AF_LIMIT_CUSTOMER: "5"
  AF_WINDOW_CUSTOMER_SEC: "120"
  AF_DAILY_CAP_MERCHANT: "0"
  AF_DAILY_CAP_DEVICE: "0"
  AF_DAILY_CAP_STAFF: "0"
  AF_DAILY_CAP_CUSTOMER: "0"
  AF_WEEKLY_CAP_MERCHANT: "0"
  AF_WEEKLY_CAP_DEVICE: "0"
  AF_WEEKLY_CAP_STAFF: "0"
  AF_WEEKLY_CAP_CUSTOMER: "0"
  # DOMAIN and BASE URLs are examples, set in your env/cluster config
  DOMAIN: "example.com"
  API_BASE_URL: "https://api.example.com"
  CORS_ORIGINS: "https://admin.example.com,https://cashier.example.com,https://app.example.com"
