apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: loyalty
  labels:
    app: loyalty-api

data:
  NODE_ENV: "production"
  WORKERS_ENABLED: "0"
  NO_HTTP: "0"
  OTEL_ENABLED: "0"
  ANTIFRAUD_GUARD: "on"
  AF_LIMIT_MERCHANT: "200"
  AF_WINDOW_MERCHANT_SEC: "3600"
  AF_LIMIT_DEVICE: "20"
  AF_WINDOW_DEVICE_SEC: "600"
  AF_LIMIT_STAFF: "60"
  AF_WINDOW_STAFF_SEC: "600"
  AF_LIMIT_CUSTOMER: "5"
  AF_WINDOW_CUSTOMER_SEC: "120"
  AF_DAILY_CAP_MERCHANT: "0"
  AF_DAILY_CAP_DEVICE: "0"
  AF_DAILY_CAP_STAFF: "0"
  AF_DAILY_CAP_CUSTOMER: "0"
  AF_WEEKLY_CAP_MERCHANT: "0"
  AF_WEEKLY_CAP_DEVICE: "0"
  AF_WEEKLY_CAP_STAFF: "0"
  AF_WEEKLY_CAP_CUSTOMER: "0"
  # DOMAIN and BASE URLs are examples, set in your env/cluster config
  DOMAIN: "example.com"
  API_BASE_URL: "https://api.example.com"
  CORS_ORIGINS: "https://admin.example.com,https://cashier.example.com,https://app.example.com"
  # Phase 4: Security & Monitoring
  # Comma-separated whitelist of admin IPs (supports prefixes like 10.0.0.* or 10.0.0.0/24)
  ADMIN_IP_WHITELIST: ""
  # Optional token to protect /metrics endpoint (set same header X-Metrics-Token on Prometheus scrape if used)
  METRICS_TOKEN: ""
  # Optional Admin TOTP secret (Base32). If set, admin requests must include X-Admin-OTP 6-digit code
  ADMIN_2FA_SECRET: ""
  # OAuth2/JWT guard for external integrations. Set JWKS URL (RS256) or HS secret (HMAC)
  OAUTH_GUARD: "on"
  OAUTH_AUDIENCE: ""
  OAUTH_ISSUER: ""
  OAUTH_JWKS_URL: ""
  OAUTH_HS_SECRET: ""
  OAUTH_REQUIRED_SCOPE: "integrations:write"
  # Per-endpoint rate limits (fallbacks exist in code if empty)
  RL_LIMIT_QUOTE: "120"
  RL_TTL_QUOTE: "60000"
  RL_LIMIT_COMMIT: "30"
  RL_TTL_COMMIT: "60000"
  RL_LIMIT_REFUND: "10"
  RL_TTL_REFUND: "60000"
  # JSON map of merchant multipliers, e.g. {"M-1":2, "M-2":0.5}
  RL_MERCHANT_MULTIPLIERS: "{}"
