apiVersion: v1
kind: ConfigMap
metadata:
  name: cashier-config
  namespace: loyalty
  labels:
    app: loyalty-cashier
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_BASE_URL: "https://api.example.com"
