apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loyalty
resources:
  - namespace.yaml
  - configmap-api.yaml
  - secret-api.example.yaml # replace with your real Secret before apply
  - deployment-api.yaml
  - service-api.yaml
  - ingress-api.yaml
  - hpa-api.yaml
  - pdb-api.yaml
  # Admin
  - configmap-admin.yaml
  - deployment-admin.yaml
  - service-admin.yaml
  - ingress-admin.yaml
  - hpa-admin.yaml
  - pdb-admin.yaml
  # Cashier
  - configmap-cashier.yaml
  - deployment-cashier.yaml
  - service-cashier.yaml
  - ingress-cashier.yaml
  - hpa-cashier.yaml
  - pdb-cashier.yaml
  # Miniapp
  - configmap-miniapp.yaml
  - deployment-miniapp.yaml
  - service-miniapp.yaml
  - ingress-miniapp.yaml
  - hpa-miniapp.yaml
  - pdb-miniapp.yaml
  # Bridge (internal service)
  - configmap-bridge.yaml
  - deployment-bridge.yaml
  - service-bridge.yaml
  - pdb-bridge.yaml
  # Namespace-wide policies
  - networkpolicy-default-deny.yaml
