apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: loyalty
  labels:
    app: loyalty-api
stringData:
  # Database
  DB_PASSWORD: change_me_db
  DATABASE_URL: postgresql://loyalty:$(DB_PASSWORD)@postgres:5432/loyalty

  # Core secrets
  ADMIN_KEY: change_me_admin_key
  QR_JWT_SECRET: change_me_qr_secret
  ADMIN_SESSION_SECRET: change_me_session_secret

  # Telegram Alerts (optional)
  ALERT_TELEGRAM_BOT_TOKEN: ""
  ALERT_TELEGRAM_CHAT_ID: ""
